steps:
#  - command: ls
  - plugins:
      - "ssh://git@bitbucket.org/ROKT/upload-sarif-buildkite-plugin.git":
          repository: 'dotnet-spider'
          commit: ${BUILDKITE_COMMIT} # Need to get the commit_sha from an env variable

# updated script