steps:
  - label: ":microscope: SARIF "
    commands:
      - "export file_value='file'"
      - "env | grep file"
    env:
      file_value: file_value
    plugins:
      - seek-oss/aws-sm#v2.3.1:
          env:
            SARIFT_SECRET: "sarif-token"
      - "ssh://git@github.com/ROKT/upload-sarif-buildkite-plugin.git#74a289599e0ecafe4fff9e5010e6bb1b5d33696c":
          repository: 'dotnet-spider'
          sarift: "SARIFT_SECRET"
          commit: ${BUILDKITE_COMMIT}
          file: "file_value"
      