steps:
  - label: ":microscope: SARIF "
    commands:
      - "./scripts/prepare-file.sh"
    plugins:
      - seek-oss/aws-sm#v2.3.1:
          env:
            SARIFT_SECRET: "sarif-token"
      - "ssh://git@github.com/ROKT/upload-sarif-buildkite-plugin.git#10843746bbea39c2de21532d3005770e28b3d4cc":
          repository: 'dotnet-spider'
          sarift: "SARIFT_SECRET"
          commit: ${BUILDKITE_COMMIT}
          file: "file_value"
      