steps:
  - label: ":microscope: SARIF "
    plugins:
      - seek-oss/aws-sm#v2.0.0:
          env:
              TOKEN: sarif-token
      - "ssh://git@bitbucket.org/ROKT/upload-sarif-buildkite-plugin.git#6d51890fda73bfc56664826f1a6c438c77e81d3a":
          repository: 'dotnet-spider'
          commit: ${BUILDKITE_COMMIT} # Need to get the commit_sha from an env variable
          token: $${TOKEN}
      - docker#v3.3.0:
          image: alpine
          command: ["ls"]