steps:
  - label: ":microscope: SARIF "
    plugins:
      - seek-oss/aws-sm#v2.0.0:
          env:
              SARIFTOKEN: "arn:aws:secretsmanager:us-west-2:035088524874:secret:sarif-token-RgG91g"
      - docker#v3.3.0:
          image: alpine
          environment: 
            - SARIFTOKEN
          command: ['echo $SARIFTOKEN']
      - "ssh://git@bitbucket.org/ROKT/upload-sarif-buildkite-plugin.git#42f2833929e39fd3e1c09abe08f20da6c8cc95a6":
          repository: 'dotnet-spider'
          commit: ${BUILDKITE_COMMIT} # Need to get the commit_sha from an env variable
          sariftoken: ${SARIFTOKEN}
      