steps:
  - label: ":microscope: SARIF "
    commands:
      - "env | grep SARIFT"
    plugins:
      - seek-oss/aws-sm#v2.3.1:
          env:
            SARIFT: "arn:aws:secretsmanager:us-west-2:035088524874:secret:sarif-token-RgG91g"
      - "ssh://git@bitbucket.org/ROKT/upload-sarif-buildkite-plugin.git#0261f38c724de62e8091309b188138136e5bf0b3":
          repository: 'dotnet-spider'
          env: SARIFT
          sarift: $SARIFT
          commit: ${BUILDKITE_COMMIT}
          #sariftoken: "value"
      