steps:
  - command: ls
  - plugins:
      - "ssh://git@bitbucket.org/ROKT/upload-sarif-buildkite-plugin.git#f076c732393f549919300ad5af7abfd5c4c78178":
          repository: 'dotnet-spider'
          commit: ${BUILDKITE_COMMIT} # Need to get the commit_sha from an env variable