steps:
  - command: ls
  - plugins:
      - "ssh://git@bitbucket.org/ROKT/upload-sarif-buildkite-plugin.git#da51fc5730d39948e16e4adce8b627397de09682":
          repository: 'dotnet-spider'
          commit: ${BUILDKITE_COMMIT} # Need to get the commit_sha from an env variable