steps:
  - label: ":microscope: SARIF "
    commands:
      - "./scripts/prepare-file.sh"
    plugins:
      - seek-oss/aws-sm#v2.3.1:
          env:
            SARIFT_SECRET: "sarif-token"
      - "ROKT/upload-sarif-plugin#v1.0.0":
          repository: 'dotnet-spider'
          sarift: "SARIFT_SECRET"
          commit: ${BUILDKITE_COMMIT}
      