steps:
  - label: ":microscope: SARIF "
    commands:
      - echo SARIFTOKEN: $${SARIF_TOKEN}
    env: 
      SARIFTOKEN
    plugins:
      - seek-oss/aws-sm#v2.3.1:
          env:
            SARIFTOKEN: "arn:aws:secretsmanager:us-west-2:035088524874:secret:sarif-token-RgG91g"
      - docker#v3.3.0:
          image: alpine
          environment: 
            - "SARIFTOKEN"
          propogate-environment: true
      - "ssh://git@bitbucket.org/ROKT/upload-sarif-buildkite-plugin.git#a1a23f0eaf6712e5c94f4124c25be23becd4b936":
          repository: 'dotnet-spider'
          commit: ${BUILDKITE_COMMIT} # Need to get the commit_sha from an env variable
          sariftoken: "SARIFTOKEN"
      