steps:
  - label: ":microscope: SARIF "
    commands:
      - "echo SARIF plugin"
    plugins:
      - seek-oss/aws-sm#v2.3.1:
          env:
            SARIFT_SECRET: "sarif-token"
      - "ssh://git@bitbucket.org/ROKT/upload-sarif-buildkite-plugin.git#0e85827333912a987948a3e29f07e95295ff44e9":
          repository: 'dotnet-spider'
          sarift: "SARIFT_SECRET"
          commit: ${BUILDKITE_COMMIT}
      