steps:
  - label: ":microscope: SARIF "
    commands:
      - "echo Preparing SARIF file for Github"
      - "file=$(gzip -c sarif.txt | base64)"
      - "export file"
    plugins:
      - seek-oss/aws-sm#v2.3.1:
          env:
            SARIFT_SECRET: "sarif-token"
      - "ssh://git@github.com/ROKT/upload-sarif-buildkite-plugin.git#e859334e8536070ab9adf737df1db21311dbbeaf":
          repository: 'dotnet-spider'
          sarift: "SARIFT_SECRET"
          commit: ${BUILDKITE_COMMIT}
          file: "file"
      