steps:
  - label: ":microscope: SARIF "
    plugins:
      - seek-oss/aws-sm#v2.0.0:
          env:
              TOKEN: sarif-token
      - "ssh://git@bitbucket.org/ROKT/upload-sarif-buildkite-plugin.git#6b1ff75659932203ae8b74f68d66ac386ad9ea07":
          repository: 'dotnet-spider'
          commit: ${BUILDKITE_COMMIT} # Need to get the commit_sha from an env variable
          token: ${TOKEN}
      - docker#v3.3.0:
          image: alpine
          command: ["ls"]