steps:
  - label: ":microscope: SARIF "
    commands:
      - "env | grep SARIFT"
    plugins:
      - seek-oss/aws-sm#v2.3.1:
          env:
            SARIFT: "arn:aws:secretsmanager:us-west-2:035088524874:secret:sarif-token-RgG91g"
      - "ssh://git@bitbucket.org/ROKT/upload-sarif-buildkite-plugin.git#1da7e226ffd5cd6bcdeef65d643aa7d7f509eee8":
          repository: 'dotnet-spider'
          env: SARIFT
          sarift: $SARIFT
          commit: ${BUILDKITE_COMMIT}
          #sariftoken: "value"
      