steps:
  - label: ":microscope: SARIF "
    plugins:
      - seek-oss/aws-sm#v2.0.0:
          env:
              SARIFTOKEN: "arn:aws:secretsmanager:us-west-2:035088524874:secret:sarif-token-RgG91g"
      - docker#v3.3.0:
          image: alpine
          environment: 
            - SARIFTOKEN
          command: ['echo $SARIFTOKEN']
      - "ssh://git@bitbucket.org/ROKT/upload-sarif-buildkite-plugin.git#6c74defec421ece26cc7ea1b48b7220f2b156559":
          repository: 'dotnet-spider'
          commit: ${BUILDKITE_COMMIT} # Need to get the commit_sha from an env variable
          sariftoken: ${SARIFTOKEN}
      