steps:
  - label: ":microscope: SARIF "
    plugins:
      - seek-oss/aws-sm#v2.0.0:
          env:
              SARIFTOKEN: "arn:aws:secretsmanager:us-west-2:035088524874:secret:sarif-token-RgG91g"
      - "ssh://git@bitbucket.org/ROKT/upload-sarif-buildkite-plugin.git#91366ce70e88c92b703be69539b78089eeaa4e6c":
          repository: 'dotnet-spider'
          commit: ${BUILDKITE_COMMIT} # Need to get the commit_sha from an env variable
          sariftoken: SARIFTOKEN
      - docker#v3.3.0:
          image: alpine
          environment: 
            - SARIFTOKEN