steps:
  - label: ":microscope: SARIF "
    commands:
      - "echo SARIFTOKEN: $${SARIFTOKEN}"
    env: 
      SARIFTOKEN
    plugins:
      - seek-oss/aws-sm#v2.3.1:
          env:
            SARIFTOKEN: "arn:aws:secretsmanager:us-west-2:035088524874:secret:sarif-token-RgG91g"
      - docker#v3.3.0:
          image: alpine
          environment: 
            - "SARIFTOKEN"
          propogate-environment: true
      - ROKT/upload-sarif-buildkite-plugin:
          repository: 'dotnet-spider'
          commit: \$SARIFTOKEN
          sariftoken: ${SARIFTOKEN}
      