steps:
#  - command: ls
  - plugins:
      - ROKT/upload-sarif#v1.0.0:
          repository: 'dotnet-spider'
          commit: ${BUILDKITE_COMMIT} # Need to get the commit_sha from an env variable

# updated script