steps:
  - label: ":microscope: SARIF "
    commands:
      - "echo Preparing SARIF file for Github"
      - "file=$(gzip -c sarif.txt | base64)"
      - "export file"
      - "echo $file"
    plugins:
      - seek-oss/aws-sm#v2.3.1:
          env:
            SARIFT_SECRET: "sarif-token"
      - "ssh://git@github.com/ROKT/upload-sarif-buildkite-plugin.git#d62fc184f265c4f7df0d8ee8ce0ead7994c45b8e":
          repository: 'dotnet-spider'
          sarift: "SARIFT_SECRET"
          commit: ${BUILDKITE_COMMIT}
          file: "file"
      